apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: login-system
    app.kubernetes.io/instance: login-system-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: login-system
spec:
  selector:
    app: login-system
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080